### PR TITLE
chore: run black formatting for Python code

### PR DESCRIPTION
**Pull request by manuelzander**
Ran `black` against `pipelines` code

### CODE REVIEW

**Comment by manuelzander** [comment]
@rsyi tests are passing locally, but here failing due to `DefaultCredentialsError` ("File /var/tmp/credentials.json is not a valid json file.") Has the `secrets.BIGQUERY_JSON` changed?

**Comment by rsyi** [comment]
Huh that's really weird - I'll look into it. Thanks, @manuelzander for the PRs! :)

**Comment by biomunky** [comment]
related to this-ish, it's probably worth setting up editorconfig too - https://editorconfig.org/

**Comment by rsyi** [comment]
@manuelzander You know what - I think it's because secrets are just not accessible through pull requests. Considering the tests don't actually need to make a connection (they just mock return some datasets), it would probably make sense to just mock and patch things more heavily. I'll make sure everything looks good locally then just go ahead and merge. WDYT?

@biomunky Huh never used that before, but it sounds like a great idea. I'll open an issue.

**Comment by manuelzander** [comment]
> @manuelzander You know what - I think it's because secrets are just not accessible through pull requests. Considering the tests don't actually need to make a connection (they just mock return some datasets), it would probably make sense to just mock and patch things more heavily. I'll make sure everything looks good locally then just go ahead and merge. WDYT?
> 
> @biomunky Huh never used that before, but it sounds like a great idea. I'll open an issue.

Sounds good to me! I'll look into the issue with the secrets as well

**Comment by rsyi** [comment]
Yeah local tests + QA pass. Merging!

**Pull request merged**
